# Generated by Django 2.0.5 on 2018-07-09 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20180709_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupimage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.ImageModel', verbose_name='图片'),
        ),
    ]
