# Generated by Django 2.0.5 on 2018-07-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20180720_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='mark',
            field=models.CharField(default='', max_length=100, verbose_name='水印图片'),
        ),
        migrations.DeleteModel(
            name='ImageMark',
        ),
    ]
