# Generated by Django 2.0.5 on 2018-07-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_imagemodel_cates'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='cates',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='种类字符串'),
        ),
    ]
