# Generated by Django 2.0.5 on 2018-07-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20180720_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='mark',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='download_nums',
            field=models.IntegerField(default=0, verbose_name='下载量'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='upload_nums',
            field=models.IntegerField(default=0, verbose_name='上传量'),
        ),
    ]
