# Generated by Django 2.0.5 on 2018-07-09 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_groupimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likeship',
            options={'verbose_name': '点赞/收藏', 'verbose_name_plural': '点赞/收藏'},
        ),
        migrations.AddField(
            model_name='likeship',
            name='name',
            field=models.CharField(choices=[('like', '点赞'), ('collection', '收藏')], default='like', max_length=10, verbose_name='点赞/收藏'),
        ),
        migrations.AlterField(
            model_name='likeship',
            name='add_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='收藏点赞时间'),
        ),
    ]
