# Generated by Django 2.0.5 on 2018-07-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_imagemodel_cates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='学号'),
        ),
    ]
