# Generated by Django 2.0.5 on 2018-07-17 07:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20180717_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='收藏时间')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
            },
        ),
        migrations.CreateModel(
            name='DownloadShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='下载时间')),
            ],
            options={
                'verbose_name': '下载',
                'verbose_name_plural': '下载',
            },
        ),
        migrations.AlterModelOptions(
            name='likeship',
            options={'verbose_name': '点赞', 'verbose_name_plural': '点赞'},
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='cates',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='heigth',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='width',
        ),
        migrations.RemoveField(
            model_name='likeship',
            name='name',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='collection_nums',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='if_sign',
            field=models.BooleanField(default=False, verbose_name='签约'),
        ),
        migrations.AlterField(
            model_name='likeship',
            name='add_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='点赞时间'),
        ),
        migrations.AddField(
            model_name='downloadship',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.ImageModel', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='downloadship',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.ImageModel', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
    ]
