# Generated by Django 2.0.5 on 2018-07-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20180717_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='pattern',
            field=models.CharField(default='png', max_length=10, verbose_name='格式'),
        ),
    ]
