# Generated by Django 2.0.5 on 2018-07-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_imagemodel_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='cates',
            field=models.CharField(default='', max_length=200, verbose_name='种类字符串'),
        ),
    ]
