# Generated by Django 2.0.5 on 2018-07-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_imagemodel_cates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m', verbose_name='图片'),
        ),
    ]
