# Generated by Django 2.0.5 on 2018-07-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_auto_20180718_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fan_nums',
            field=models.IntegerField(default=0, verbose_name='粉丝量'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='follow_nums',
            field=models.IntegerField(default=0, verbose_name='关注者量'),
        ),
    ]
