# Generated by Django 2.0.5 on 2018-07-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='collection_nums',
            field=models.IntegerField(default=0, verbose_name='总收藏量'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='download_nums',
            field=models.IntegerField(default=0, verbose_name='总被下载量'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='like_nums',
            field=models.IntegerField(default=0, verbose_name='总点赞量'),
        ),
    ]
