# Generated by Django 2.0.5 on 2018-07-27 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_auto_20180727_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='add_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='关注时间'),
        ),
    ]
