# Generated by Django 2.0.5 on 2018-07-27 09:52

from django.db import migrations, models
import utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_follow_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='heads/default.png', null=True, storage=utils.storage.ImageStorage(), upload_to='heads/%Y/%m', verbose_name='头像'),
        ),
    ]
