# Generated by Django 2.0.5 on 2018-07-28 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_auto_20180727_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='image',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='user',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
